# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    profiles: ["media", "arrs", "all"]
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - bazarr_data:/config
      - myMedia:/media
    ports:
      - ${BAZARR_PORT:-6767}:6767/tcp
    depends_on:
      - radarr
      - sonarr
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    networks:
      - traefik
    labels:
      traefik.http.services.bazarr.loadbalancer.server.port: 6767
      dockpeek.tags: media

volumes:
  bazarr_data:
