# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    profiles: ["bazarr", "arrs", "media", "basic", "default", "full"]
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      BAZARR__AUTH__APIKEY: ${BAZARR_API_KEY:-}
    volumes:
      - bazarr_data:/config
      - myMedia:/media
    depends_on:
      radarr:
        condition: service_started
        required: false
      sonarr:
        condition: service_started
        required: false
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.services.bazarr.loadbalancer.server.port: 6767
      tinyauth.apps.bazarr.config.domain: bazarr.${DOMAIN_NAME}
      tinyauth.apps.bazarr.path.allow: ^/api
      homepage.group: Media Management
      homepage.name: Bazarr
      homepage.icon: sh-bazarr.webp
      homepage.href: //bazarr.${DOMAIN_NAME}
      homepage.description: Subtitles
      homepage.widget.type: bazarr
      homepage.widget.url: http://bazarr:6767
      homepage.widget.key: ${BAZARR_API_KEY:-}

volumes:
  bazarr_data:
