# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    profiles: ["media", "all"]
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      VERSION: docker
      PLEX_CLAIM: ${PLEX_CLAIM}
      ADVERTISE_IP: http://${PHYSICAL_SERVER_IP}:32400
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - plex_data:/config
      - myMedia:/mnt/media
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    labels:
      gangplank.forward: "32400/tcp"
      traefik.enable: false
      dockpeek.ports: 32400
      dockpeek.tags: media
#        - homepage.icon=emby.png
#        - homepage.href=http://emby.home/
#        - homepage.description=Media server

volumes:
  plex_data:
