# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    profiles: ["prowlarr", "configarr", "arrs", "media", "basic", "default", "full"]
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      PROWLARR__AUTH__APIKEY: ${PROWLARR_API_KEY:-}
    volumes:
      - prowlarr_data:/config
    networks:
      - traefik
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
    labels:
      traefik.enable: true
      traefik.http.services.prowlarr.loadbalancer.server.port: 9696
      tinyauth.apps.prowlarr.config.domain: prowlarr.${DOMAIN_NAME}
      tinyauth.apps.prowlarr.path.allow: ^/(api|ping|\d+/(api|download))
      homepage.group: Media Management
      homepage.name: Prowlarr
      homepage.icon: sh-prowlarr.webp
      homepage.href: //prowlarr.${DOMAIN_NAME}
      homepage.description: Indexer manager
      homepage.widget.type: prowlarr
      homepage.widget.url: http://prowlarr:9696
      homepage.widget.key: ${PROWLARR_API_KEY:-}

volumes:
  prowlarr_data:
