# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    profiles: ["media", "arrs", "all"]
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      RADARR__AUTH__APIKEY: ${RADARR_API_KEY:-}
    volumes:
      - radarr_data:/config
      - myMedia:/media
    ports:
      - ${RADARR_PORT:-7878}:7878/tcp
    depends_on:
      - prowlarr
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.http.services.radarr.loadbalancer.server.port: 7878
      homepage.group: Media Management
      homepage.name: Radarr
      homepage.icon: sh-radarr.webp
      homepage.href: //radarr.${DOMAIN_NAME}
      homepage.description: Movies
      homepage.widget.type: radarr
      homepage.widget.url: http://radarr:7878
      homepage.widget.key: ${RADARR_API_KEY:-}
      homepage.widget.enableQueue: true

volumes:
  radarr_data:
