# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  homebridge:
    container_name: homebridge
    image: homebridge/homebridge:latest
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    network_mode: host
    profiles: ["automation", "all"]
    volumes:
      - homebridge_data:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    environment:
      TZ: ${TZ}
    labels:
      traefik.enable: false
      homepage.group: Automation
      homepage.name: Homebridge
      homepage.icon: sh-homebridge.webp
      homepage.href: http://${PHYSICAL_SERVER_IP}:8581
      homepage.description: HomeKit bridge

volumes:
  homebridge_data:
