# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - 11434:11434/tcp
    profiles: ["ai", "all"]
    environment:
      OLLAMA_ORIGINS: "*"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - traefik
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    labels:
      traefik.enable: true

volumes:
  ollama_data:
