# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui
    container_name: open-webui
    volumes:
      - open_webui_data:/app/backend/data
    profiles: ["open-webui", "ai", "full"]
    environment:
      TZ: ${TZ}
      OAUTH_CLIENT_ID: ${OPEN_WEBUI_OIDC_CLIENT_ID:-}
      OAUTH_CLIENT_SECRET: ${OPEN_WEBUI_OIDC_CLIENT_SECRET:-}
      OPENID_PROVIDER_URL: ${OPEN_WEBUI_OIDC_CLIENT_ID:+https://id.${DOMAIN_NAME}/.well-known/openid-configuration}
      OAUTH_PROVIDER_NAME: Pocket ID
      ENABLE_OAUTH_SIGNUP: ${OPEN_WEBUI_OIDC_CLIENT_ID:+true}
      OAUTH_MERGE_ACCOUNTS_BY_EMAIL: ${OPEN_WEBUI_OIDC_CLIENT_ID:+true}
    networks:
      - traefik
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    labels:
      traefik.enable: true
      traefik.http.routers.open-webui.rule: "Host(`ai.${DOMAIN_NAME}`)"
      traefik.http.services.open-webui.loadbalancer.server.port: 8080
      homepage.group: AI
      homepage.name: Open WebUI
      homepage.icon: sh-open-webui.webp
      homepage.href: //ai.${DOMAIN_NAME}
      homepage.description: LLM chat UI

volumes:
  open_webui_data:
