# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: ddns-updater
    profiles: ["ddns-updater", "network", "basic", "default", "full"]
    environment:
      TZ: ${TZ}
      ROOT_URL: /
      CONFIG: >-
        {"settings": [
        {"provider": "cloudflare", "zone_identifier": "${CF_ZONE_ID}", "domain": "${PUBLIC_DOMAIN:?set PUBLIC_DOMAIN in .env}", "ttl": 1, "token": "${CF_DNS_API_TOKEN}", "ip_version": "ipv4"},
        {"provider": "cloudflare", "zone_identifier": "${CF_ZONE_ID}", "domain": "*.${PUBLIC_DOMAIN:?set PUBLIC_DOMAIN in .env}", "ttl": 1, "token": "${CF_DNS_API_TOKEN}", "ip_version": "ipv4"}
        ]}
    networks:
      - traefik
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
    labels:
      traefik.enable: true
      traefik.http.services.ddns-updater.loadbalancer.server.port: 8000
      traefik.http.routers.ddns-updater.middlewares: ${TINYAUTH_ENABLED:+tinyauth@docker}
      homepage.group: Network
      homepage.name: DDNS Updater
      homepage.icon: mdi-ip-network-outline
      homepage.href: //ddns-updater.${DOMAIN_NAME}
      homepage.description: Dynamic DNS
