# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    profiles: ["vpn", "all"]
    cap_add:
      - NET_ADMIN
    env_file:
      - ../../.env.gluetun
    networks:
      - vpn
      - traefik
    ports:
      - ${QBITTORRENT_PORT:-8081}:${QBITTORRENT_PORT:-8081}/tcp
      - ${TORRENT_PORT:-6881}:${TORRENT_PORT:-6881}/tcp
      - ${TORRENT_PORT:-6881}:${TORRENT_PORT:-6881}/udp
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    healthcheck:
      test: ["CMD", "/gluetun-entrypoint", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      dockpeek.tags: network
