# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  tailscale:
    image: tailscale/tailscale:stable
    container_name: tailscale
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - tailscale-data:/var/lib/tailscale
    environment:
      TS_AUTHKEY: ${TAILSCALE_TOKEN}
      TS_ACCEPT_DNS: 'true'
    network_mode: host
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    labels:
      traefik.enable: true
      traefik.http.services.ddns-updater.loadbalancer.server.port: 8000
      dockpeek.tags: network

volumes:
  tailscale-data:
