# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  tailscale:
    image: tailscale/tailscale:stable
    container_name: tailscale
    profiles: ["tailscale"]
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - tailscale_data:/var/lib/tailscale
    environment:
      TS_AUTHKEY: ${TAILSCALE_TOKEN}
      TS_ACCEPT_DNS: 'true'
      TS_ROUTES: ${PHYSICAL_SERVER_NETWORK}
    network_mode: host
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}

volumes:
  tailscale_data:
