# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  tailscale:
    image: tailscale/tailscale:stable
    container_name: tailscale
    profiles: ["tailscale", "full"]
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - tailscale_data:/var/lib/tailscale
    environment:
      TS_AUTHKEY: ${TAILSCALE_TOKEN}
      TS_ACCEPT_DNS: 'true'
      TS_ROUTES: ${PHYSICAL_SERVER_NETWORK}
      TS_STATE_DIR: /var/lib/tailscale
      TS_AUTH_ONCE: true
    network_mode: host
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"

volumes:
  tailscale_data:
