- resources:
    label: System
    cpu: true
    memory: true
    uptime: true
    disk: /

- openmeteo:
    label: Weather
    latitude: {{HOMEPAGE_VAR_WEATHER_LATITUDE}}
    longitude: {{HOMEPAGE_VAR_WEATHER_LONGITUDE}}
    units: metric
    cache: 5

- search:
    provider: duckduckgo
    target: _blank

- datetime:
    text_size: xl
    format:
      dateStyle: long
      timeStyle: short
