# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    networks:
      - traefik
    volumes:
      - homarr_data:/appdata
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      TZ: ${TZ}
      SECRET_ENCRYPTION_KEY: ${HOMARR_SECRET_ENCRYPTION_KEY}
    labels:
      traefik.enable: true
      traefik.http.services.homarr.loadbalancer.server.port: 7575
      homepage.group: Tools
      homepage.name: Homarr
      homepage.icon: sh-homarr.webp
      homepage.href: //homarr.${DOMAIN_NAME}
      homepage.description: Dashboard

volumes:
  homarr_data: