# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    profiles: ["homarr", "full"]
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
    networks:
      - traefik
    volumes:
      - homarr_data:/appdata
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      TZ: ${TZ}
      SECRET_ENCRYPTION_KEY: ${HOMARR_SECRET_ENCRYPTION_KEY}
      AUTH_PROVIDERS: ${HOMARR_OIDC_CLIENT_ID:+oidc,}credentials
      AUTH_OIDC_ISSUER: https://id.${DOMAIN_NAME}
      AUTH_OIDC_CLIENT_ID: ${HOMARR_OIDC_CLIENT_ID:-}
      AUTH_OIDC_CLIENT_SECRET: ${HOMARR_OIDC_CLIENT_SECRET:-}
      AUTH_OIDC_CLIENT_NAME: Pocket ID
    labels:
      traefik.enable: true
      traefik.http.services.homarr.loadbalancer.server.port: 7575
      homepage.group: Tools
      homepage.name: Homarr
      homepage.icon: sh-homarr.webp
      homepage.href: //homarr.${DOMAIN_NAME}
      homepage.description: Dashboard

volumes:
  homarr_data: