# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    profiles: ["tools", "all"]
    environment:
      HOMEPAGE_ALLOWED_HOSTS: home.${DOMAIN_NAME},${DOMAIN_NAME}
    volumes:
      - ../config/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    labels:
      traefik.enable: true
      traefik.http.routers.homepage.rule: Host(`home.${DOMAIN_NAME}`) || Host(`${DOMAIN_NAME}`)
      traefik.http.services.homepage.loadbalancer.server.port: 3000
