# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  homepage:
    image: gethomepage/homepage:latest
    container_name: homepage
    profiles: ["homepage", "tools", "basic", "default", "full"]
    environment:
      HOMEPAGE_ALLOWED_HOSTS: home.${DOMAIN_NAME},${DOMAIN_NAME},${PHYSICAL_SERVER_IP}:${HOMEPAGE_PORT:-3002}
      HOMEPAGE_VAR_WEATHER_LATITUDE: ${WEATHER_LATITUDE:-1.3521}
      HOMEPAGE_VAR_WEATHER_LONGITUDE: ${WEATHER_LONGITUDE:-103.8198}
    volumes:
      - ../config/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
    labels:
      traefik.enable: true
      traefik.http.routers.homepage.rule: Host(`home.${DOMAIN_NAME}`) || Host(`${DOMAIN_NAME}`)
      traefik.http.services.homepage.loadbalancer.server.port: 3000
      traefik.http.routers.homepage.middlewares: ${TINYAUTH_ENABLED:+tinyauth@docker}
