# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  openlist:
    image: openlistteam/openlist:latest
    container_name: openlist
    profiles: ["tools", "all"]
    user: ${OPENLIST_UID:-0}:${OPENLIST_GID:-0}
    environment:
      TZ: ${TZ}
      UMASK: ${OPENLIST_UMASK:-022}
    volumes:
      - openlist_data:/opt/openlist/data
      - myMedia:/media
    ports:
      - ${OPENLIST_PORT:-5244}:5244/tcp
      - ${OPENLIST_S3_PORT:-5245}:5245/tcp
    restart: ${UNIVERSAL_RESTART_POLICY:-unless-stopped}
    networks:
      - traefik
    labels:
      traefik.http.services.openlist.loadbalancer.server.port: 5244
      dockpeek.ports: 5244
      dockpeek.tags: tools

volumes:
  openlist_data:
