[AutoRun]
enabled=false
program=

[BitTorrent]
Session\DefaultSavePath=/media/Downloads
Session\TempPathEnabled=false

[LegalNotice]
Accepted=true

[Preferences]
Connection\UPnP=false
Downloads\SavePath=/media/Downloads
Downloads\TempPathEnabled=false
WebUI\Address=*
WebUI\AuthSubnetWhitelistEnabled=false
WebUI\LocalHostAuth=false
WebUI\CSRFProtection=false
WebUI\HostHeaderValidation=false
WebUI\ServerDomains=*
WebUI\ReverseProxySupportEnabled=true
WebUI\TrustedReverseProxiesList=172.16.0.0/12
